### PR TITLE
ci: add sync-files

### PR DESCRIPTION
**Pull request by KeisukeShima**
Related https://github.com/tier4/pre-commit-hooks-ros/pull/15#issuecomment-1031044701

Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>

### CODE REVIEW

**Review by kenji-miyake — APPROVED** [review]
Thank you! But since this is CI, I edited the title.

**Comment by kenji-miyake** [comment]
@KeisukeShima Could you merge this and run the workflow manually? :pray:

**Comment by kenji-miyake** [comment]
@KeisukeShima Also, adding https://github.com/autowarefoundation/autoware-github-actions/pull/38 is useful, I think!

**Comment by KeisukeShima** [comment]
It works! https://github.com/tier4/pre-commit-hooks-ros/pull/24#pullrequestreview-874192882

**Pull request merged**
