### PR TITLE
Add prettier-xacro

### PR DESCRIPTION
**Pull request by kenji-miyake**
For https://github.com/tier4/aip_description.iv

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Worked with this settings!

```yaml
  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: add-prettier-xacro
    hooks:
      - id: prettier-xacro
```

image

**Review by KeisukeShima — APPROVED** [review]
LGTM!

**Comment by kenji-miyake** [comment]
@KeisukeShima Could you release this as the next version?

**Comment by KeisukeShima** [comment]
@kenji-miyake Sure! I'd love to.
Added tag `v0.3.0` at 5cb102ef7da64a7788678c9b595a900860c5422a

**Comment by KeisukeShima** [comment]
https://github.com/tier4/pre-commit-hooks-ros/releases/tag/v0.3.0

**Comment by DLu** [comment]
Oh man, this is exactly what I was looking for!

**Pull request merged**
